from enum import StrEnum


class Mods(StrEnum):
    Relax = "RX"
    DifficultyAdjust = "DA"
    NightCore = "NC"
    CustomSpeed = "CS"
    DoubleTime = "DT"
    Hidden = "HD"
    FlashLight = "FL"
    ShitMod = "RE"  # REZ
    WindUp = "WU"
    Precise = "PR"
    HardRock = "HR"
    HalfTime = "HT"
    AutoPilot = "AP"
    WindDown = "WD"
    ApproachDifferent = "AD"
    Auto = "AT"
    Easy = "EZ"
    FreezeFrame = "FR"
    Mirror = "MR"
    Muted = "MU"
    NoFail = "NF"
    Random = "RD"
    ScoreV2 = "V2"
    SmallCircle = "SC"
    SuddenDeath = "SD"
    Perfect = "PF"
    Traceable = "TC"
    Synesthesia = "SY"
    NoMod = "NM"
